# Site settings
title: Parsons MPS Communication Design
description: >
  A one-year graduate degree program for Digital Product Design.
email: email@email.com
url: ""

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-minifier
