---
title: Parsons MPS Communication Design
timezone: UTC
collections:
  posts:
    title: Projects
    output: true
  students:
    title: Students
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Digital Product Design
description: 'A one-year graduate degree program for Digital Product Design.

'
is explore open: false
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-minifier
