---
title: Parsons MPS Communication Design
timezone: America/New_York
collections:
  curriculum:
    title: Curriculum
    output: true
  faculty:
    title: Faculty
    output: true
  texts:
    title: Page intro texts
    output: true
  posts:
    title: Projects
    output: true
  students:
    title: Students
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: curriculum
  values:
    credit: 
    pmcd: 
    expand: false
    outbound_link: 
- scope:
    path: ''
    type: students
  values:
    list: 
- scope:
    path: ''
    type: faculty
  values:
    list: 
- scope:
    path: ''
    type: posts
  values:
    type: image
    images:
    - file: 
      creator: 
      link: 
subtitle: Digital Product Design
sidebar_text: Parsons School of Design — MPS Communication Design — Digital Product
  Design
is_explore_open: true
initial_filter: 2021
show_countdown: true
countdown_date: 2021-05-13 09:00:00.000000000 Z
countdown_hero: uploads/mpsc2021.gif
countdown_sticker: Congrats MPSCD 2021!
background_image: 
background_color: "#d5ffc3"
og_image: "/uploads/og-image.png"
url: http://www.newschool.edu
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-minifier
