---
title: Parsons MPS Communication Design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'A one-year graduate degree program for Digital Product Design.

'
email: email@email.com
url: ''
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-minifier
