---
title: Parsons MPS Communication Design
timezone: America/New_York
collections:
  curriculum:
    title: Curriculum
    output: true
  faculty:
    title: Faculty
    output: true
  posts:
    title: Projects
    output: true
  students:
    title: Students
    output: true
  texts:
    title: Texts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Digital Product Design
is_explore_open: false
background_image: "/uploads/windows_xp_bliss.jpg"
background_color: "#ffffff"
url: http://www.newschool.edu
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-minifier
defaults:
  -
    scope:
      path: ""
      type: "curriculum"
    values:
      credit:
      pmcd:
      learn_more: