---
title: Parsons MPS Communication Design
timezone: America/New_York
collections:
  posts:
    title: Projects
    output: true
  students:
    title: Students
    output: true
  texts:
    title: Texts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Digital Product Design
is explore open: false
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-minifier
