---
title: Parsons  MPS Communication Design
timezone: America/New_York
collections:
  curriculum:
    title: Curriculum
    output: true
  faculty:
    title: Faculty
    output: true
  texts:
    title: Page intro texts
    output: true
  posts:
    title: Projects
    output: true
  students:
    title: Students
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: curriculum
  values:
    credit:
    pmcd:
    expand: false
    outbound_link:
- scope:
    path: ''
    type: students
  values:
    list:
- scope:
    path: ''
    type: faculty
  values:
    list:
- scope:
    path: posts
    type: projects
  values:
    images:
      src:
      creator:
      link:
subtitle: Digital Product Design
sidebar_text: Parsons School of Design — MPS Communication Design — Digital Product
  Design
is_explore_open: false
initial_filter: 2020
background_image: "/uploads/windows_xp_bliss.jpg"
background_color: "#ffffff"
og_image: "/uploads/windows_xp_bliss.jpg"
url: http://www.newschool.edu
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-minifier
