name: Automatic build/deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  pages:    write
jobs:
  github-pages:
    name:    GitHub Pages
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Pages
      id:   pages
      uses: actions/configure-pages@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Configure bundler path
      run: bundle config set path 'vendor/bundle'
    - name: Cache Ruby gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup ImageMagick
      uses: mfinelli/setup-imagemagick@v6
      # Ubuntu doesn’t have version `magick`, otherwise.
    - name: Install dependencies and build
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
    - name: Upload output
      uses: actions/upload-pages-artifact@v3
    - name: Deploy Pages
      uses: actions/deploy-pages@v4
